// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaASJmrHAmMTc-2BU0bif4xwy6H3FSDjE',
    appId: '1:320903346377:web:19cae5b41df238f7933518',
    messagingSenderId: '320903346377',
    projectId: 'generalms-b6a03',
    authDomain: 'generalms-b6a03.firebaseapp.com',
    storageBucket: 'generalms-b6a03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL9znKRnYG1ahuaKcyIiuwc-bdXxKH_pI',
    appId: '1:320903346377:android:6f1cc44173370072933518',
    messagingSenderId: '320903346377',
    projectId: 'generalms-b6a03',
    storageBucket: 'generalms-b6a03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJXHVo1pvUSWmkZU6x9hfS6_m7KevuAc',
    appId: '1:320903346377:ios:dc200de2374477c4933518',
    messagingSenderId: '320903346377',
    projectId: 'generalms-b6a03',
    storageBucket: 'generalms-b6a03.appspot.com',
    iosBundleId: 'com.example.generalms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJJXHVo1pvUSWmkZU6x9hfS6_m7KevuAc',
    appId: '1:320903346377:ios:dc200de2374477c4933518',
    messagingSenderId: '320903346377',
    projectId: 'generalms-b6a03',
    storageBucket: 'generalms-b6a03.appspot.com',
    iosBundleId: 'com.example.generalms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaASJmrHAmMTc-2BU0bif4xwy6H3FSDjE',
    appId: '1:320903346377:web:617cdd1d99abc077933518',
    messagingSenderId: '320903346377',
    projectId: 'generalms-b6a03',
    authDomain: 'generalms-b6a03.firebaseapp.com',
    storageBucket: 'generalms-b6a03.appspot.com',
  );
}
